### ISSUE TITLE
getImage() throws OOM

### ISSUE THREAD

**Issue by MarcoFalke** [MER-C/wiki-java#78]
When calling something like ```commons.getImage("David_White_at_EduWiki_2013.webm");```, I am getting the following error.

    INFO: Fetching URL https://upload.wikimedia.org/wikipedia/commons/d/df/David_White_at_EduWiki_2013.webm
    Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2271)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:122)

I doubt increasing the heap space is the proper way to fix this, so maybe creating a [temp file](http://stackoverflow.com/a/12073300/2084795) will help to fix this issue?

**Comment by MarcoFalke** [comment]
Or what about adding a new parameter to getImage()?
```void getImage(String title, File destination)```
